version: '3.8'

services:
  user_service:
    build: ./services/user_service
    ports:
      - '3001:3001'
    environment:
      - DATABASE_URL=mysql://myuser:mypassword@mysql:3306/mydb
    depends_on:
      - mysql

  mysql:
    image: mysql:8.0
    container_name: mysql-container
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: mydb
      MYSQL_USER: myuser
      MYSQL_PASSWORD: mypassword
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql

volumes:
  mysql-data:
